# Generated by Django 4.0 on 2022-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, null=True)),
                ('auteur', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('prix', models.FloatField(null=True)),
                ('categorie', models.CharField(choices=[('Sciences', 'Sciences'), ('Arts', 'Arts'), ('Histoire', 'Histoire'), ('Informatique', 'Informatique')], max_length=200, null=True)),
                ('dateEdition', models.DateField(null=True)),
                ('imageLivre', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
