# Generated by Django 4.0 on 2022-01-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Livrer', 'Livrer'), ('En cours', 'En cours'), ('Hors service', 'Hors service')], max_length=200, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookStore.client')),
                ('livre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookStore.livre')),
            ],
        ),
    ]
